title: System of a Mind
description: "An exploration of the systems of thought that govern our lives."

# GitHub Pages project site settings
url: https://nodesman.github.io
baseurl: /systemofmind
permalink: pretty

# Theme
remote_theme: just-the-docs/just-the-docs

# Theme options
search_enabled: true
color_scheme: nil

aux_links:
  "View on GitHub":
    - "https://github.com/nodesman/systemofmind"
nav_external_links_new_tab: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
  - scope:
      path: "legacy_files"
    values:
      nav_exclude: true

sass:
  quiet_deps: true
