source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.8"
gem "jekyll-remote-theme", "~> 0.4.3"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"

group :jekyll_plugins do
  gem "jekyll-remote-theme", "~> 0.4.3"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

